### ISSUE TITLE
Whitelisted components  / dev dependencies / Injection

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-component-installer#2]
@weierophinney 

Good evening,

Right now, it is possible to whitelist modules for automatic injection in zf config file. However, the target config file is always the same, that is, the modules.config.php file. I think that the development.config.php file (if available) should be preferred for injection when a package is listed as development dependencies (require-dev vs require).

Thanks you.

---

Originally posted by @nuxwin at https://github.com/zendframework/zend-component-installer/issues/55

**Comment by kpicaza** [comment]
Hello, Is this issue still active? And do you think that can be a good first issue for me? 
Thanks for your great work;-D

**Comment by weierophinney** [comment]
@kpicaza Go for it!

**Comment by weierophinney** [comment]
Fixed with #9
